stages:
  - build

  # Tests the app, shows the tests logs and info in the test section of the pipeline
  - test

  # Creates resource group, virtual machine and SQL DataBase for deployment using terraform (OpenTofu) if they don't already exist
  - pre-deploy

  # Uses ansible to log into th deployment virtual machine, setup project dependendencies and runs the project using docker compose
  - deploy

  # ─────────────────────────────────────────────────────────────────────────────
  # Destroy jobs (manual only)
  # - All jobs run outside the custom runner to avoid deleting themselves.
  # - Three destroy options exist:
  #   1. destroy-deployment-infrastructure: Deletes only the deployment infra (rg-team18-deploy - contains deployment VM, SQL DB...)
  #   2. destroy-gitlab-runner-infrastructure: Deletes only the GitLab runner infra (rg-team18)
  #   3. destroy-all-infrastructure: Deletes everything (runner + deployment + NetworkWatcherRG)
  # - After destroying the runner, re-run azure-setup.sh to recreate it before next pipeline
  # ─────────────────────────────────────────────────────────────────────────────
  - destroy


# ─────────────────────────────────────────────────────────────────────────────
# Runs in custom azure runner in shell mode, make a simple build
build-application:
  stage: build
  tags:
    - azure
    - shell
  script:
    - echo "Running build stage in pipeline $(date)" >> /var/log/cd-gitlab-pipeline.log
    - echo "========== BUILD STAGE =========="
    # export the GitLab Runner’s UID/GID into HOST_UID and HOST_GID (needed in the docker compose for permissions)
    - export HOST_UID=$(id -u)
    - export HOST_GID=$(id -g)
    - docker compose up --build build-stage-team18-int4-java-app
    - echo "========== BUILD STAGE COMPLETED SUCCESSFULLY =========="
  artifacts:
    paths:
      - gradlew
      - gradle/wrapper/
  only:
    - dev
    - main

## ─────────────────────────────────────────────────────────────────────────────
#
## ─────────────────────────────────────────────────────────────────────────────
## Runs in our custom azure runner in shell mode, so it needs to remove previously existing containers (--remove-orphans) for this stage
## Tests the app using the docker compose configuration
## We need to specify user (gitlab-runner user), because otherwise docker uses the default user (root) to execute the command, which means that the files created with the build won't be able to be deleted by gitlab on the next test stage pipeline execution
test-application:
  stage: test
  tags:
    - azure
    - shell
  dependencies:
    - build-application
  script:
    - echo "Running test stage in pipeline $(date)" >> /var/log/cd-gitlab-pipeline.log
    - echo "========== TEST STAGE =========="
    # Need to create .env file (using CI/CD vars) in order to execute tests succesfully because of the Dotenvinitializer class
    - bash ./set-env.sh
    - docker compose run --user "$(id -u):$(id -g)" -e GRADLE_USER_HOME=/team18-project/.gradle --remove-orphans team18-integration4-test
    - echo "========== TEST STAGE COMPLETED SUCCESSFULLY =========="
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  only:
    - dev
    - main
## ─────────────────────────────────────────────────────────────────────────────

## ─────────────────────────────────────────────────────────────────────────────
## Runs in our custom docker container (contains all dependencies) in our custom azure runner
## Checks if deployment environment exists or no
## If it doesn't exist it creates the deployment RG, VM & SQL DB with the correct firewall rules
azure-pre-deployment-setup:
  stage: pre-deploy
  image: anir333/team18-int4:latest
  tags:
    - azure
    - docker
  script:
    - echo "========== PRE-DEPLOY STAGE =========="
    - cd ./azure-config/deployment/ || exit 1
    - bash ./pre-deploy-check.sh
    - echo "========== PRE-DEPLOY STAGE COMPLETED SUCCESSFULLY =========="
  only:
    - main
## ─────────────────────────────────────────────────────────────────────────────


# ─────────────────────────────────────────────────────────────────────────────
# Runs in our custom azure runner in our custom docker image
# Uses ansible to connect to deployment VM, set up dependencies, delete previous app and run the new one
deploy-application:
  stage: deploy
  image: anir333/team18-int4:latest
  tags:
    - azure
    - docker
  script: bash ./azure-config/stages/deploy-application.sh
  only:
    - main
# ─────────────────────────────────────────────────────────────────────────────



# Destroy Stages:
# All destroy stages DO NOT run in our custom runner to ensure they are fully executed and not stopped mid-process by deleting themselves

# ─────────────────────────────────────────────────────────────────────────────
# Only runs when manually triggered
#  Deletes only the deployment infrastructure (Deployment RG, VM & SQL DB)
destroy-deployment-infrastructure:
  stage: destroy
  image: anir333/team18-int4:latest
  when: manual
  allow_failure: true
  variables:
    DESTROY_DEPLOY: "true"
  script:
    - bash ./azure-config/deployment/azure-login.sh
    - bash ./azure-config/stages/destroy-infrastructure.sh
  only:
    - main
# ─────────────────────────────────────────────────────────────────────────────

# ─────────────────────────────────────────────────────────────────────────────
# Only runs when manually triggered
#  Deletes gitlab runner infrastructure (RG & VM)
destroy-gitlab-runner-infrastructure:
  stage: destroy
  image: anir333/team18-int4:latest
  when: manual
  allow_failure: true
  variables:
    DESTROY_RUNNER: "true"
  script:
    - bash ./azure-config/deployment/azure-login.sh
    - bash ./azure-config/stages/destroy-infrastructure.sh
  only:
    - main
# ─────────────────────────────────────────────────────────────────────────────


# ─────────────────────────────────────────────────────────────────────────────
# Only runs when manually triggered
# Destroys all azure infra, (Runner: RG & VM) (Deployment: RG, VM & SQL DB)
destroy-all-infrastructure:
  stage: destroy
  image: anir333/team18-int4:latest
  when: manual
  allow_failure: true
  variables:
    DESTROY_ALL: "true"
  script:
    - bash ./azure-config/deployment/azure-login.sh
    - bash ./azure-config/stages/destroy-infrastructure.sh
  only:
    - main
# ─────────────────────────────────────────────────────────────────────────────