services:
    nginx:
        image: nginx:latest
        container_name: nginx-reverse-proxy
        ports:
            - "80:80"
            - "443:443"
        environment:
            - SUB_DOMAIN=team18-int4
            - PROFILE_ACTIVE=prod
        volumes:
            - ./azure-config/nginx/templates:/etc/nginx/templates
            - ./azure-config/nginx/letsencrypt:/etc/letsencrypt
        networks:
            - team18-network
        depends_on:
            team18-int4-java-app:
                condition: service_started

    team18-int4-java-app:
        build: .
        container_name: team18-int4-java-app
        environment:
            - PROFILE_ACTIVE=prod
        networks:
            - team18-network

    build-stage-team18-int4-java-app:
        image: gradle:jdk21
        container_name: build-stage-team18-int4-java-app

        # Pass the host’s UID/GID into the container as env vars:
        environment:
            - HOST_UID=${HOST_UID}
            - HOST_GID=${HOST_GID}

        volumes:
            - "./:/team18-app/"
        working_dir: "/team18-app/"

        # Run Gradle, then chown everything back to HOST_UID:HOST_GID before exit:
        command:
            - sh
            - -c
            - |
                gradle wrapper --gradle-version 8.13 \
                  && ./gradlew --build-cache assemble \
                  && chown -R "$HOST_UID":"$HOST_GID" .

    postgres_ebike_db:
        image: postgres:17.2-alpine
        container_name: team18-prod-db
        restart: always
        environment:
            POSTGRES_DB: 'ebike'
            POSTGRES_USER: 'dev'
            POSTGRES_PASSWORD: 'bike'
        ports:
            - '5055:5432'
        volumes:
            - ebike-db:/var/lib/postgresql/data

    team18-integration4-test:
        image: gradle:jdk21
        container_name: team18-integration4-test
        working_dir: /team18-project/
        volumes:
            -   "./:/team18-project/"
        command: ./gradlew check
        depends_on:
            - postgres_ebike_test_db
        networks:
            - ebike-test-network

    postgres_ebike_test_db:
        image: postgres:17.2-alpine
        container_name: postgres_ebike_test_db
        environment:
            POSTGRES_DB: 'ebike_test'
            POSTGRES_USER: 'dev'
            POSTGRES_PASSWORD: 'bike'
        ports:
            - '5065:5432'
        volumes:
            - ebike-test-db:/var/lib/postgresql/data
        networks:
            - ebike-test-network

networks:
    ebike-test-network:
        driver: bridge
    team18-network:
        driver: bridge


volumes:
    ebike-db:
    ebike-test-db:

