# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/team18-int4.duckdns.org
cert = /etc/letsencrypt/live/team18-int4.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/team18-int4.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/team18-int4.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/team18-int4.duckdns.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = c72c4f5d9211c6dfd7b34463abb6428e
pref_challs = dns-01,
authenticator = dns-duckdns
dns_duckdns_token = b4bb4460-f9d0-42fc-a063-e1dbadd11014
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
