#spring.datasource.url=jdbc:postgresql://db-az-sql-team18.postgres.database.azure.com:5432/flexibleserverdb?sslmode=require
spring.datasource.url=jdbc:postgresql://team18sqldb.postgres.database.azure.com:5432/postgres
spring.datasource.username=team18admin
spring.datasource.password=${AZURE_SQL_DB_PASSWORD}

spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:/static/data/data.sql
spring.jpa.defer-datasource-initialization=true


spring.baseurl=https://team18-int4.duckdns.org
