#spring.datasource.url=jdbc:postgresql://db-az-sql-team18.postgres.database.azure.com:5432/flexibleserverdb?sslmode=require
spring.datasource.url=jdbc:postgresql://postgres_ebike_db:5432/ebike
spring.datasource.username=dev
spring.datasource.password=bike

spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:/static/data/data.sql
spring.jpa.defer-datasource-initialization=true


