spring.application.name=demo
spring.profiles.active=dev
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://localhost:5055/ebike
spring.datasource.username=dev
spring.datasource.password=bike