spring.application.name=demo
#spring.profiles.active=dev
spring.jpa.open-in-view=false
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5055/ebike
spring.datasource.username=dev
spring.datasource.password=bike