server.port=8080
spring.application.name=demo
spring.profiles.active=dev
spring.jpa.open-in-view=false
logging.level.be.kdg.integration4=debug


spring.datasource.url=jdbc:postgresql://localhost:5055/ebike
spring.datasource.username=dev
spring.datasource.password=bike

workbench.apikey=${WORKBENCH_API_KEY}

workbench.api.url=https://testbench.raoul.dev

#spring.mvc.static-path-pattern=/static/**
