spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:/static/data/data.sql
spring.jpa.defer-datasource-initialization=true
spring.baseurl=http://localhost:8080
