services:
    nginx:
        image: nginx:latest
        container_name: anir-nginx-reverse-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/templates:/etc/nginx/templates
            - ./nginx/letsencrypt:/etc/letsencrypt
        environment:
            - SERV_ADDR=anir-infra3.duckdns.org
        networks:
            - anir-backend-container-communication-network
        depends_on:
            - anir-java-app
            - anir-nodejs-app
            - anir-python-flask-app

    anir-java-app:
        build: ./JavaSpringBootApp/
        container_name: anir-java-app
        ports:
            - '8080:8080'
        environment:
            SPRING_DATASOURCE_URL: 'jdbc:postgresql://anir-postgres-db:5432/anir-db'
            SPRING_DATASOURCE_USERNAME: 'anir'
            SPRING_DATASOURCE_PASSWORD: 'anir'
        networks:
            - anir-backend-container-communication-network
        depends_on:
            - anir-postgres-db

    anir-postgres-db:
        image: postgres:17.2-alpine
        restart: always
        container_name: anir-postgres-db
        environment:
            POSTGRES_DB: 'anir-db'
            POSTGRES_USER: 'anir'
            POSTGRES_PASSWORD: 'anir'
        ports:
            - '5061:5432'
        volumes:
            - anir-db-volume:/var/lib/postgresql/data
        networks:
            - anir-backend-container-communication-network

volumes:
    anir-db-volume:

networks:
    anir-backend-container-communication-network:
        driver: bridge
