GET http://localhost:8080/api/workshops
Accept: application/json

###

POST http://localhost:8080/api/register
Content-Type: application/json
Accept: application/json

{
  "role": "ROLE_CUSTOMER",
  "name": "Name",
  "email": "customer@gmail.com",
  "password": "password",
  "phoneNumber": "123",
  "workshopId": null
}

###

POST http://localhost:8080/api/start-test
Content-Type: application/json

{
  "testbenchNumber": 3,
  "testType": "STRESS",
  "emailBikeOwner": "cust@email.com",
  "chassisNumber": "XYZ123456789",
  "bikeBrand": "Trek",
  "bikeSize": "M",
  "productionDate": 2020,
  "type": "Mountain",
  "powertrain": "Shimano",
  "enginePowerMax": 500,
  "mileage": 1000,
  "accuCapacity": 500,
  "enginePowerNominal": 400,
  "gearType": "Manual",
  "maxSupport": 30,
  "engineTorque": 75,
  "engineType": "Electric"
}

###

POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

email=tech@email.com&password=password